# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='slogan',
        ),
    ]
