# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-11 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_profesion_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='prueba',
        ),
    ]
