# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_profesion_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='start',
            field=models.DateField(),
        ),
    ]
